[package]
name = "easechat-recorder"
version = "0.0.0"
authors = ["luojia65 <me@luojia.cc>"]
edition = "2018"

[dependencies]
chrono = "0.4"

[dependencies.rusqlite]
version = "0.16"
features = ["chrono"]
