[package]
name = "easechat-recorder"
version = "0.0.0"
authors = ["luojia65 <me@luojia.cc>"]
edition = "2018"

[dependencies]
chrono = "0.4"
ws = "*"
clap = { version = "2.32", features = ["yaml"] }
rusqlite = { version = "0.16", features = ["chrono"] }
